
name = "nordic-computers-db"

pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2024-10-29"

[[d1_databases]]
binding = "NORDIC_DB"
database_name = "nordic-computers-demo-db"
database_id = "3dd79ec3-a2de-41af-8253-bde2c77ca344"