name = "nordic-computers-demo"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2024-10-29"


[vars]
WORKER_AUTH_KEY = "C0A7A37B95B7F1E73A7F9B3A87A5EFFB2FB8834863A6071E19902E37F99A1CD3"