name = "nordic-computers-demo"
pages_build_output_dir = ".svelte-kit/cloudflare"

compatibility_date = "2024-10-22"

[[d1_databases]]
binding = "NORDIC_DB"
database_name = "nordic-computers-demo-db"
database_id = "3dd79ec3-a2de-41af-8253-bde2c77ca344"
preview_database_id = "NORDIC_DB"


[vars]
ENVIRONMENT="REMOTE" # LOCAL | REMOTE